name: Backend CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["backend/**", ".github/workflows/backend.yml"]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]
    paths: ["backend/**", ".github/workflows/backend.yml"]

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven" 
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Dar permissão de execução para o Maven Wrapper
        run: chmod +x mvnw

      - name: Build, Testes e Sonar Analysis
        working-directory: ./backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B -Dspring.profiles.active=test -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.5.0.6356:sonar
      
      - name: Validar Relatório de Cobertura
        run: test -f target/site/jacoco/jacoco.xml
